-- Generated by 9am-build: loads the test framework and all spec files for a resource.

local resourceDir = arg[1]
if not resourceDir then
  io.stderr:write("[9am-build] missing resource directory argument\n")
  os.exit(1)
end

resourceDir = resourceDir:gsub("\\", "/")

-- Extend package.path so tests can require resource modules.
package.path = resourceDir .. "/?.lua;"
  .. resourceDir .. "/?/init.lua;"
  .. package.path

local assetsDir = os.getenv("NINEAM_TEST_ASSETS")
if assetsDir then
  assetsDir = assetsDir:gsub("\\", "/")
  package.path = assetsDir .. "/?.lua;" .. package.path
end

local framework = dofile((assetsDir or ".") .. "/framework.lua")
local helpers = dofile((assetsDir or ".") .. "/helpers.lua")

_G.describe = describe
_G.it = it
_G.beforeEach = beforeEach
_G.afterEach = afterEach
_G.expect = expect
_G.TestHelpers = helpers

for i = 2, #arg do
  local testFile = arg[i]
  print("[9am-build] loading " .. testFile)
  local ok, err = xpcall(function()
    dofile(testFile)
  end, debug.traceback)
  if not ok then
    io.stderr:write("[9am-build] failed to load " .. testFile .. ":\n" .. tostring(err) .. "\n")
    print("9AM_TEST_SUMMARY passed=0 failed=1 total=1")
    os.exit(1)
  end
end

print("")
print("[9am-build] running tests...")
print("")

local results = framework.run()
local total = results.passed + results.failed

print("")
print(string.format(
  "9AM_TEST_SUMMARY passed=%d failed=%d total=%d",
  results.passed,
  results.failed,
  total
))

if results.failed > 0 then
  os.exit(1)
end
